// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function reducer(action, state) {
  if (action) {
    return /* Update */Block.__(0, [/* record */[/* top */state[/* top */0] - 1 | 0]]);
  } else {
    return /* Update */Block.__(0, [/* record */[/* top */state[/* top */0] + 1 | 0]]);
  }
}

exports.reducer = reducer;
/* No side effect */
