// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function className(classes) {
  if (classes) {
    return List.fold_left((function (acc, classItem) {
                  if (classItem !== undefined) {
                    var str = classItem;
                    if (str === "") {
                      return acc;
                    } else {
                      return acc + (" " + str);
                    }
                  } else {
                    return acc;
                  }
                }), "", classes);
  } else {
    return "";
  }
}

var Color = 0;

exports.Color = Color;
exports.className = className;
/* No side effect */
