// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function map_list_result(func, result) {
  if (result !== undefined) {
    return $$Array.of_list(List.rev($$Array.fold_left((function (acc, item) {
                          if (item !== undefined) {
                            return /* :: */[
                                    Curry._1(func, Caml_option.valFromOption(item)),
                                    acc
                                  ];
                          } else {
                            return acc;
                          }
                        }), /* [] */0, result)));
  } else {
    return /* array */[];
  }
}

var Symbols = 0;

exports.Symbols = Symbols;
exports.map_list_result = map_list_result;
/* No side effect */
